baseURL = 'https://yakimant.io'
languagecode = "en"
defaultcontentlanguage = "en"
title = 'yakimant'
theme = 'hugo-coder'

[params]
  author = "Anton Iakimov"
  info = "Lead DevOps Engineer"
  description = "Anton Iakimov's personal website"
  keywords = "devops,personal"
  gravatar = "yakimant@gmail.com"

  since = 2023

  colorScheme = "auto"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/yakimant/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/yakimant/"
[[params.social]]
  name = "Cal.com"
  icon = "fa fa-calendar fa-2x"
  weight = 3
  url = "https://cal.com/yakimant"
